# -*- coding: utf-8 -*-
"""DiscountMate T3 - Tile product scraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCX32Ntf02nGYnCANd_QqS-g4sWntHJi
"""

pip install ultralytics opencv-python

import os
import cv2
from ultralytics import YOLO

# ------------------------
# Configuration
# ------------------------
MODEL_PATH = "weights.pt"          # your YOLOv8 weights
IMAGE_PATH = "page_006.jpg"     # catalogue page image
OUTPUT_DIR = "exported_tiles"
IMG_SIZE = 640
CONF_THRESHOLD = 0.25

os.makedirs(OUTPUT_DIR, exist_ok=True)

# ------------------------
# Load model
# ------------------------
model = YOLO(MODEL_PATH)

# ------------------------
# Run inference
# ------------------------
results = model.predict(
    source=IMAGE_PATH,
    imgsz=IMG_SIZE,
    conf=CONF_THRESHOLD,
    verbose=False
)

result = results[0]
image = cv2.imread(IMAGE_PATH)

# ------------------------
# Export each detected tile
# ------------------------
for i, box in enumerate(result.boxes):
    # Bounding box coordinates
    x1, y1, x2, y2 = map(int, box.xyxy[0])

    # Crop image
    crop = image[y1:y2, x1:x2]

    if crop.size == 0:
        continue

    # Class and confidence
    class_id = int(box.cls[0])
    class_name = model.names[class_id]
    confidence = float(box.conf[0])

    # Output filename
    filename = f"{class_name}_{i:03d}_{confidence:.2f}.jpg"
    output_path = os.path.join(OUTPUT_DIR, filename)

    # Save tile
    cv2.imwrite(output_path, crop)

print("Tile export completed")
